(define (problem random-redflix-problem)
    (:domain redflix)

    (:objects
        c1 c2 c3 c4 c5 c6 c7 c8 c9 c10 c11 c12 c13 w1 w2 - content
        day1 day2 day3 day4 day5 day6 day7 day8 day9 day10 day11 - day
    )

    (:init
        (predecessor c1 c2)
        (predecessor c2 c3)
        (predecessor c4 c5)
        (predecessor c5 c6)
        (predecessor c6 c7)
        (predecessor c7 c8)
        (predecessor c9 c10)
        (predecessor c12 c13)

        (parallel w2 c13)

        (is_wanted c4)
        (is_wanted c3)
        (is_wanted c5)
        (is_wanted c1)
        (is_wanted c2)
        (is_wanted c6)
        (is_wanted c11)
        (is_wanted c8)

        (watched w1)
        (watched w2)

        (= (duration c1) 65)
        (= (duration c2) 87)
        (= (duration c3) 92)
        (= (duration c4) 97)
        (= (duration c5) 76)
        (= (duration c6) 120)
        (= (duration c7) 95)
        (= (duration c8) 51)
        (= (duration c9) 108)
        (= (duration c10) 90)
        (= (duration c11) 59)
        (= (duration c12) 63)
        (= (duration c13) 97)
        (= (duration w1) 83)
        (= (duration w2) 56)

        (yesterday day1 day2)
        (yesterday day2 day3)
        (yesterday day3 day4)
        (yesterday day4 day5)
        (yesterday day5 day6)
        (yesterday day6 day7)
        (yesterday day7 day8)
        (yesterday day8 day9)
        (yesterday day9 day10)
        (yesterday day10 day11)

        (= (day_duration day1) 0)
        (= (day_duration day2) 0)
        (= (day_duration day3) 0)
        (= (day_duration day4) 0)
        (= (day_duration day5) 0)
        (= (day_duration day6) 0)
        (= (day_duration day7) 0)
        (= (day_duration day8) 0)
        (= (day_duration day9) 0)
        (= (day_duration day10) 0)
        (= (day_duration day11) 0)

        (= (priority day1) 1)
        (= (priority day2) 2)
        (= (priority day3) 3)
        (= (priority day4) 4)
        (= (priority day5) 5)
        (= (priority day6) 6)
        (= (priority day7) 7)
        (= (priority day8) 8)
        (= (priority day9) 9)
        (= (priority day10) 10)
        (= (priority day11) 11)

        (= (total-days) 0)
        (= (remaining-content) 9)
    )

    (:goal
        (and
            (= (remaining-content) 0)
        )
    )

    (:metric minimize (total-days))
)
