(define (problem random-redflix-problem)
    (:domain redflix)

    (:objects
        c1 c2 c3 c4 c5 c6 c7 c8 c9 c10 c11 c12 c13 c14 c15 c16 c17 c18 w1 w2 w3 - content
        day1 day2 day3 day4 day5 day6 day7 day8 day9 day10 day11 - day
    )

    (:init
        (predecessor c4 c5)
        (predecessor c7 c8)
        (predecessor c10 c11)
        (predecessor c11 c12)
        (predecessor c13 c14)
        (predecessor c16 c17)

        (parallel c9 c1)
        (parallel c7 c10)
        (parallel c7 c15)
        (parallel c13 c10)
        (parallel c11 c15)
        (parallel c3 c10)
        (parallel c12 c16)
        (parallel c5 c18)
        (parallel c11 c4)
        (parallel w1 c12)
        (parallel w2 c16)

        (is_wanted c1)
        (is_wanted c10)
        (is_wanted c3)
        (is_wanted c7)
        (is_wanted c2)

        (watched w1)
        (watched w2)
        (watched w3)

        (= (duration c1) 61)
        (= (duration c2) 51)
        (= (duration c3) 112)
        (= (duration c4) 47)
        (= (duration c5) 106)
        (= (duration c6) 94)
        (= (duration c7) 87)
        (= (duration c8) 90)
        (= (duration c9) 41)
        (= (duration c10) 69)
        (= (duration c11) 58)
        (= (duration c12) 76)
        (= (duration c13) 85)
        (= (duration c14) 110)
        (= (duration c15) 84)
        (= (duration c16) 98)
        (= (duration c17) 111)
        (= (duration c18) 78)
        (= (duration w1) 103)
        (= (duration w2) 116)
        (= (duration w3) 73)

        (yesterday day1 day2)
        (yesterday day2 day3)
        (yesterday day3 day4)
        (yesterday day4 day5)
        (yesterday day5 day6)
        (yesterday day6 day7)
        (yesterday day7 day8)
        (yesterday day8 day9)
        (yesterday day9 day10)
        (yesterday day10 day11)

        (= (day_duration day1) 0)
        (= (day_duration day2) 0)
        (= (day_duration day3) 0)
        (= (day_duration day4) 0)
        (= (day_duration day5) 0)
        (= (day_duration day6) 0)
        (= (day_duration day7) 0)
        (= (day_duration day8) 0)
        (= (day_duration day9) 0)
        (= (day_duration day10) 0)
        (= (day_duration day11) 0)

        (= (total-days) 0)
        (= (remaining-content) 7)
    )

    (:goal
        (and
            (= (remaining-content) 0)
        )
    )

    (:metric minimize (total-days))
)
