(define (problem random-redflix-problem)
    (:domain redflix)

    (:objects
        c1 c2 c3 c4 c5 c6 c7 c8 c9 c10 c11 c12 c13 c14 c15 c16 c17 c18 c19 c20 w1 w2 w3 w4 - content
        day1 day2 day3 day4 day5 day6 day7 day8 day9 day10 day11 day12 - day
    )

    (:init
        (predecessor c1 c2)
        (predecessor c3 c4)
        (predecessor c5 c6)
        (predecessor c6 c7)
        (predecessor c7 c8)
        (predecessor c8 c9)
        (predecessor c9 c10)
        (predecessor c11 c12)
        (predecessor c18 c19)
        (predecessor c19 c20)
        (predecessor w1 c9)
        (predecessor w3 c11)

        (parallel c19 c1)
        (parallel c13 c20)
        (parallel c9 c4)
        (parallel c3 c20)
        (parallel c17 c19)
        (parallel c9 c5)
        (parallel c12 c4)
        (parallel w4 c16)

        (is_wanted c17)
        (is_wanted c8)
        (is_wanted c10)
        (is_wanted c13)

        (watched w1)
        (watched w2)
        (watched w3)
        (watched w4)

        (= (duration c1) 114)
        (= (duration c2) 64)
        (= (duration c3) 99)
        (= (duration c4) 74)
        (= (duration c5) 88)
        (= (duration c6) 74)
        (= (duration c7) 69)
        (= (duration c8) 49)
        (= (duration c9) 103)
        (= (duration c10) 52)
        (= (duration c11) 86)
        (= (duration c12) 46)
        (= (duration c13) 87)
        (= (duration c14) 104)
        (= (duration c15) 91)
        (= (duration c16) 43)
        (= (duration c17) 111)
        (= (duration c18) 72)
        (= (duration c19) 110)
        (= (duration c20) 57)
        (= (duration w1) 109)
        (= (duration w2) 77)
        (= (duration w3) 77)
        (= (duration w4) 43)

        (yesterday day1 day2)
        (yesterday day2 day3)
        (yesterday day3 day4)
        (yesterday day4 day5)
        (yesterday day5 day6)
        (yesterday day6 day7)
        (yesterday day7 day8)
        (yesterday day8 day9)
        (yesterday day9 day10)
        (yesterday day10 day11)
        (yesterday day11 day12)

        (= (day_duration day1) 0)
        (= (day_duration day2) 0)
        (= (day_duration day3) 0)
        (= (day_duration day4) 0)
        (= (day_duration day5) 0)
        (= (day_duration day6) 0)
        (= (day_duration day7) 0)
        (= (day_duration day8) 0)
        (= (day_duration day9) 0)
        (= (day_duration day10) 0)
        (= (day_duration day11) 0)
        (= (day_duration day12) 0)

        (= (total-days) 0)
        (= (remaining-content) 8)
    )

    (:goal
        (and
            (= (remaining-content) 0)
        )
    )

    (:metric minimize (total-days))
)
